version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql/
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: EvXTC3R7Sef5aB725hKv
      MYSQL_DATABASE: suitecrm
      MYSQL_USER: suitecrm
      MYSQL_PASSWORD: B3fyAKRyFpaMR5vyPMJz

  suitecrm:
    build: 7.11.3
    ports:
      - "80:80"
    links:
      - "db"
    environment:
      DB_TYPE: mysql
      DB_MANAGER: MysqliManager
      DB_HOST_NAME: db
      MYSQL_ROOT_PASSWORD: EvXTC3R7Sef5aB725hKv
      DATABASE_NAME: suitecrm
      DB_USER_NAME: suitecrm
      DB_PASSWORD: B3fyAKRyFpaMR5vyPMJz
    volumes:
      - 'suitecrm_data:/var/www/html'
    depends_on:
      - db

volumes:
  db_data:
    driver: local
  suitecrm_data:
    driver: local
