version: '3'

volumes:
  db-data:

services:
  suitecrm:
    build: 7.11.3
    ports:
      - "80:80"
    links:
      - "db"
    environment:
      DB_TYPE: mysql
      DB_MANAGER: MysqliManager
    depends_on:
      - db
  dbdata:
    image: tianon/true
    volumes:
      - db-data:/var/lib/mysql
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: EvXTC3R7Sef5aB725hKv
      MYSQL_DATABASE: suitecrm
      MYSQL_USER: suitecrm
      MYSQL_PASSWORD: B3fyAKRyFpaMR5vyPMJz
