suitecrm:
  build: 7.11.3
  ports:
    - "80:80"
  links:
    - "db"
  environment:
    DB_TYPE: mysql
    DB_MANAGER: MysqliManager
dbdata:
  image: tianon/true
  volumes:
    - /var/lib/mysql
db:
  image: 'hypriot/rpi-mysql'
  volumes_from:
    - dbdata
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: EvXTC3R7Sef5aB725hKv
    MYSQL_DATABASE: suitecrm
    MYSQL_USER: suitecrm
    MYSQL_PASSWORD: B3fyAKRyFpaMR5vyPMJz
